- name: Build Docker Image
  run: |
    docker build -t myusername/my-app:${{ github.sha }} .
    echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    docker push myusername/my-app:${{ github.sha }}
